#ifndef __UI_PAL_H__
#define __UI_PAL_H__

#define COLOR_BUTTONS	(92)
#define UI_COLOR_DISPLAY
#define CMD_TITLE

#define GRADATION_LEVEL (64)

enum
{
	FONT_COLOR_BLANK = 0,
	FONT_COLOR_NORMAL,
#ifdef UI_COLOR_DISPLAY
	FONT_COLOR_BLANK_INVERSE,
	FONT_COLOR_NORMAL_INVERSE,
	FONT_COLOR_NORMAL2,
	FONT_COLOR_SPECIAL,
	FONT_COLOR_WHITE,
	BUTTON_COLOR_RED,
	BUTTON_COLOR_YELLOW,
	BUTTON_COLOR_GREEN,
	BUTTON_COLOR_BLUE,
	BUTTON_COLOR_PURPLE,
	BUTTON_COLOR_PINK,
	BUTTON_COLOR_AQUA,
	
	BUTTON_COLOR_SILVER,
	BUTTON_COLOR_NAVY,
	BUTTON_COLOR_LIME,
	
	SYSTEM_COLOR_BACKGROUND,
	SYSTEM_COLOR_FRAMEMEDIUM,
	SYSTEM_COLOR_FRAMELIGHT,
	SYSTEM_COLOR_FRAMEDARK,
	OSDBAR_COLOR_FRAMEMEDIUM,
	OSDBAR_COLOR_FRAMELIGHT,
	OSDBAR_COLOR_FRAMEDARK,
	OSDBAR_COLOR_DEFAULTBAR,
	CURSOR_COLOR,
#ifdef CMD_TITLE
	TITLE_COLOR_RED,
	TITLE_COLOR_YELLOW,
	TITLE_COLOR_GREEN,
	TITLE_COLOR_BLUE,
	TITLE_COLOR_PURPLE,
	TITLE_COLOR_WHITE,
	TITLE_COLOR_BLACK,
	TITLE_COLOR_WHITE_1,
	TITLE_COLOR_WHITE_2,
	TITLE_COLOR_WHITE_3,
	TITLE_COLOR_WHITE_4,
	TITLE_COLOR_WHITE_5,
	TITLE_COLOR_BLACK_1,
	TITLE_COLOR_BLACK_2,
	TITLE_COLOR_BLACK_3,
	TITLE_COLOR_BLACK_4,
	TITLE_COLOR_BLACK_5,
#endif /* CMD_TITLE */	

	FONT_COLOR_LIGHT,
	FONT_COLOR_DARK,
	TITLEBAR_START,
	TITLEBAR_END,
	GRADATION_COLOR,
	END_OF_COLOR = GRADATION_COLOR + GRADATION_LEVEL - 1,

#endif /* UI_COLOR_DISPLAY */

	MAX_COLORTABLE
};

#endif /* __UI_PAL_H__ */
